config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  match '/home', to: 'static_pages#home',  via: 'get' 
  match '/help',to: 'static_pages#help',  via: 'get' 
  match '/about',   to: 'static_pages#about',  via: 'get' 
  match '/contact', to: 'static_pages#contact',  via: 'get' 
 

  root :to => 'static_pages#home'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
		def self.search(search, page)
	 where(['upper(fecha) like?', "%#{search}%".upcase]).paginate(page: page, per_page: 6).order("fecha")
    end
    # Validar que los atributos sean obligatorios
	validates :nombre, :presence => true
	validates :direccion, :presence => true
	validates :hora, :presence => true
	validates :valor, :presence => true
	# valida la longitud de un campo, tanto la longitud minima como la maxima
	validates :nombre, length: { minimum: 5, maximum: 50 }
	# Valida si un atributo es numerico
	validates :valor, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    #@clientes = Cliente.all
    @clientes = Cliente.search(params[:search], params[:page])
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente creado exitosamente.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :celular, :barrio, :direccion, :referenciadir, :fecha, :hora, :ocacion, :valor)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente, :html => { :class => 'form­horizontal' } ) do |f| %>    
          <% if @cliente.errors.any? %> 
            <div id="error_explanation">   
              <h2><%=   pluralize(@cliente.errors.count,   "error")   %>   prohibited   this   cliente   from  
              being saved:</h2>    
              <ul>    
                <% @cliente.errors.full_messages.each do |message| %>   
              <li><%= message %></li>   
          <% end %>    
              </ul> 
          </div> 
    <% end %> 

  <div class="form­-group"> 
    <label for="nombre" class="col­-sm­-3 control­-label">Nombre</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :nombre, class: 'form­-control' %> 
      </div> 
  </div> 
  <div class="form­-group"> 
    <label for="telefono" class="col­-sm­-3 control­-label">Teléfono</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :telefono, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="celular" class="col­-sm­-3 control­-label">Celular</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :celular, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="barrio" class="col­-sm­-3 control­-label">Barrio</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :barrio, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="direccion" class="col­-sm­-3 control­-label">Dirección</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :direccion, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="direccion" class="col­-sm­-3 control­-label">Referencia</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :referenciadir, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="hora" class="col­-sm­-3 control­-label">Hora</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :hora, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="fecha" class="col­-sm­-3 control­-label">Fecha</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :fecha, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="ocacion" class="col­-sm­-3 control­-label">Ocación</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :ocacion, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="form­-group"> 
    <label for="valor" class="col­-sm­-3 control­-label">Valor</label> 
      <div class="col­-md­-4">     
         <%= f.input_field :valor, class: 'form­-control' %> 
      </div> 
  </div>
  <div class="actions"> 
    <%= f.submit "GUARDAR", class: "btn btn­success btn­sm" %> 
  </div>  
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to 'VER', @cliente %> |
<%= link_to 'ATRAS', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<%= form_tag clientes_path, :method => 'get' do %>
<% content_tag :label do %>
Fecha del evento:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Buscar", :name => nil %>
<% end %>
<% end %>

<table class="table table-bordered">
  <thead>
    <tr class="info">
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Barrio</th>
      <th>Direccion</th>
      <th>Referenciadir</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Ocacion</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr class="success">
        <td><%= cliente.nombre %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.celular %></td>
        <td><%= cliente.barrio %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.referenciadir %></td>
        <td><%= cliente.fecha %></td>
        <td><%= cliente.hora %></td>
        <td><%= cliente.ocacion %></td>
        <td><%= cliente.valor %></td>
        <td><%= link_to 'VER', cliente %></td>
        <td><%= link_to 'EDITAR', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'ELIMINAR', cliente, method: :delete, data: { confirm: 'Quiere Eliminar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'NUEVO CLIENTE', new_cliente_path %>

<%= will_paginate @clientes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' %>
<br>
Clientes: <%= @clientes.count %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'ATRAS', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<p>
  <strong>Barrio:</strong>
  <%= @cliente.barrio %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Referenciadir:</strong>
  <%= @cliente.referenciadir %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @cliente.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @cliente.hora %>
</p>

<p>
  <strong>Ocacion:</strong>
  <%= @cliente.ocacion %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @cliente.valor %>
</p>

<%= link_to 'EDITAR', edit_cliente_path(@cliente) %> |
<%= link_to 'ATRAS', clientes_path %>

app/views/layouts/_footer.html.erb
<footer class="footer"> 
  <small> 
	Por: WILLIAM ROJAS. Todos los derechos reservados © 2015 ::. 
  </small> 
  <nav> 
	<ul>   
		<li><a href="http://www.fiestaycumbia.comyr.com/">Fiesta y Cumbia</a></li> 
	</ul> 
  </nav> 
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'INICIO', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'CLIENTES', clientes_path, class: 'navbar-brand' %>
<%= link_to 'ACERCA DE NOSOTROS', href="http://www.fiestaycumbia.comyr.com/", class: 'navbar-brand' %>
<%= link_to 'CONTACTENOS', contact_path, class: 'navbar-brand' %>
<%= link_to 'AYUDA?', help_path, class: 'navbar-brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fiesta y cumbia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fica" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>FIESTA Y CUMBIA</h1>

app/views/static_pages/contact.html.erb
<h1>FIESTA Y CUMBIA</h1>

app/views/static_pages/help.html.erb
<h1>FIESTA Y CUMBIA</h1>

app/views/static_pages/home.html.erb
<html>
<head>
<style type="text/css">
body {
	background-color: #848484;
}
.Estilo2 {
	font-size: 70px;
	font-weight: bold;
}
.Estilo3 {color: #FFFF00}
.Estilo4 {color: #0000FF}
.Estilo8 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
}
.Estilo10 {color: #FF0066}
.Estilo17 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
	font-style: italic;
}
.Estilo18 {color: #CCFF66}
.Estilo19 {color: #CCFF33}
.Estilo20 {color: #CCFF00}
.Estilo21 {color: #CC00FF}
.Estilo22 {color: #FF33FF}
.Estilo23 {color: #FF9900}
.Estilo24 {color: #00FFFF}
.Estilo25 {color: #3399FF}
.Estilo26 {color: #666633}
.Estilo27 {color: #FFFF99}
.Estilo30 {color: #33FF00}
.Estilo31 {color: #FF0000}
.Estilo35 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
}
.Estilo36 {
	font-size: 24px
}
.Estilo39 {
	color: #ffff00;
	font-weight: bold;
	font-size: 36px;
}
.Estilo40 {
	font-size: 18px;
	font-weight: bold;
	font-style: italic;
	color: #CCCC00;
}
#ueles{
	background: #def;
}
sub{color: #000}
</style>
<script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
<link href="SpryAssets/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
</head>

<body>
<div align="right">
  <p><span class="Estilo2"><span class="Estilo3">
  </span></span></p>
</div>
<div id="ueles" align="center">
	<ul align="center">
      <p class="Estilo40">Porros, Cumbias</p>
      <p class="Estilo40">Fandangos, Mapalé</p>
      <p class="Estilo40">Sanjuanero</p>
      <p class="Estilo40">Merengues <sub>Folclóricos</sub></p>
      <p class="Estilo40">Vallenatos <sub>Tocados con clarinete u otro pito</sub></p>
	</ul>
</div>
<p align="center" class="Estilo39">&nbsp; </p>
<p align="center" class="Estilo35 Estilo36">Fiesta y cumbia es uno más de los tantos grupos folclóricos que alegra tus   
<p align="center" class="Estilo8">fiestas, desfiles, banquetes, paseos y reuniones sociales... en <u>Medellín</u>.   
<p align="center" class="Estilo8">Luchamos por mantener vivas nuestras raíces, rescatando de nuestros ancestros,  
<p align="center" class="Estilo8">las tradiciones culturales que nos representan como colombianos.  
<p align="center" class="Estilo8">Damos a conocer, de una  u otra forma,  a las nuevas generaciones,  un pasado  
<p align="center" class="Estilo8">que solo se puede apreciar  con nuestras expresiones culturales.  
<p align="center" class="Estilo17">¡<span class="Estilo18">F</span><span class="Estilo19">i</span><span class="Estilo20">e</span><span class="Estilo21">sta</span><span class="Estilo22"> y </span><span class="Estilo23">Cum</span><span class="Estilo24">bia</span><span class="Estilo25"> ale</span><span class="Estilo26">gra</span><span class="Estilo27"> tus</span> <span class="Estilo24">ev</span><span class="Estilo31">en</span><span class="Estilo30">tos</span>!  
  <div align="center"><pre class="Estilo40">Nuestro repertorio es variado:
	Vale la pena aclarar que todo este   
	repertorio suena en formato folclórico.</pre></div>
</body>
</html>